import type { Casino } from "@/lib/database.types";

// Demo data for all entry types
export const demoCasinos: Casino[] = [
  {
    id: "demo-1",
    name: "Royal Vegas Casino",
    slug: "royal-vegas-casino",
    logo_url: "https://via.placeholder.com/150?text=Royal+Vegas",
    bonus: "Welcome Bonus: $500 + 100 Free Spins",
    license: "Malta Gaming Authority",
    description: "Royal Vegas Casino offers a premium gaming experience with over 500 slot games, live dealer tables, and a comprehensive loyalty program. Established in 2000, it has become one of the most trusted online casinos in the industry.",
    country: "Malta",
    payment_methods: ["Visa", "Mastercard", "PayPal", "Skrill", "Neteller", "Bitcoin"],
    rating_avg: 4.5,
    rating_count: 234,
    entry_type: "casino",
    promo_code: "ROYAL500",
    promo_code_expires_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    editorial_rating: 4.7,
    verified: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-2",
    name: "Betway Casino",
    slug: "betway-casino",
    logo_url: "https://via.placeholder.com/150?text=Betway",
    bonus: "100% Match Bonus up to $1,000",
    license: "UK Gambling Commission",
    description: "Betway Casino is a leading online casino platform known for its extensive game library, fast payouts, and excellent customer support. The casino features games from top providers and offers a mobile-optimized experience.",
    country: "United Kingdom",
    payment_methods: ["Visa", "Mastercard", "PayPal", "Bank Transfer", "Ethereum"],
    rating_avg: 4.7,
    rating_count: 189,
    entry_type: "casino",
    editorial_rating: 4.8,
    verified: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-3",
    name: "LeoVegas Casino",
    slug: "leovegas-casino",
    logo_url: "https://via.placeholder.com/150?text=LeoVegas",
    bonus: "Up to $1,200 + 120 Free Spins",
    license: "Malta Gaming Authority",
    description: "LeoVegas is the \"King of Mobile Casino\" with an award-winning mobile platform. It offers a wide selection of slots, table games, and live casino options. The casino is known for its quick withdrawals and 24/7 customer service.",
    country: "Sweden",
    payment_methods: ["Visa", "Mastercard", "PayPal", "Trustly", "Zimpler"],
    rating_avg: 4.6,
    rating_count: 312,
    entry_type: "casino",
    promo_code: "LEO1200",
    promo_code_expires_at: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    editorial_rating: 4.6,
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-4",
    name: "Casino Player Blog",
    slug: "casino-player-blog",
    logo_url: "https://via.placeholder.com/150?text=Blog",
    bonus: "Real player experiences and bonus guides",
    license: "N/A",
    description: "A blog where players share their real experiences with online casinos, including detailed reviews, bonus guides, and tips for getting the most out of casino offers.",
    country: undefined,
    payment_methods: undefined,
    rating_avg: 4.3,
    rating_count: 45,
    entry_type: "blog",
    external_url: "https://example.com/casino-blog",
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-5",
    name: "888 Casino Sister Site",
    slug: "888-casino-sister",
    logo_url: "https://via.placeholder.com/150?text=888+Sister",
    bonus: "Exclusive Welcome Bonus: $400 + 88 Free Spins",
    license: "UK Gambling Commission",
    description: "Sister site of 888 Casino offering exclusive bonuses and promotions. Same trusted license and gaming experience with special offers for new players.",
    country: "United Kingdom",
    payment_methods: ["Visa", "Mastercard", "PayPal", "Skrill", "Neteller", "Apple Pay"],
    rating_avg: 4.4,
    rating_count: 156,
    entry_type: "sister-site",
    promo_code: "SISTER888",
    promo_code_expires_at: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    editorial_rating: 4.5,
    verified: true,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-5b",
    name: "Bet365 Sister Casino",
    slug: "bet365-sister-casino",
    logo_url: "https://via.placeholder.com/150?text=Bet365+Sister",
    bonus: "Welcome Package: $500 + 200 Free Spins",
    license: "UK Gambling Commission",
    description: "Sister site of Bet365 Casino with exclusive promotions and bonuses. Same reliable gaming platform and trusted license.",
    country: "United Kingdom",
    payment_methods: ["Visa", "Mastercard", "PayPal", "Skrill", "Neteller"],
    rating_avg: 4.6,
    rating_count: 203,
    entry_type: "sister-site",
    promo_code: "SISTER365",
    promo_code_expires_at: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000).toISOString(),
    editorial_rating: 4.7,
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-5c",
    name: "LeoVegas Sister Site",
    slug: "leovegas-sister-site",
    logo_url: "https://via.placeholder.com/150?text=LeoVegas+Sister",
    bonus: "Exclusive Bonus: $300 + 100 Free Spins",
    license: "Malta Gaming Authority",
    description: "Sister site of LeoVegas offering mobile-optimized gaming experience with exclusive bonuses for new players.",
    country: "Sweden",
    payment_methods: ["Visa", "Mastercard", "PayPal", "Trustly", "Zimpler"],
    rating_avg: 4.3,
    rating_count: 145,
    entry_type: "sister-site",
    promo_code: "SISTERLEO",
    promo_code_expires_at: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000).toISOString(),
    editorial_rating: 4.4,
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-6",
    name: "Casino Review Portal",
    slug: "casino-review-portal",
    logo_url: "https://via.placeholder.com/150?text=Review",
    bonus: "Personal reviews, pros & cons, alternatives, registration help",
    license: "N/A",
    description: "A comprehensive review site that provides personal casino reviews, lists pros and cons, suggests alternatives, helps with registration, provides promo codes, assists with withdrawals, and offers detailed reviews.",
    country: undefined,
    payment_methods: undefined,
    rating_avg: 4.2,
    rating_count: 78,
    entry_type: "review-site",
    external_url: "https://example.com/review-service",
    verified: false,
    is_featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-6b",
    name: "Casino Analyst Pro",
    slug: "casino-analyst-pro",
    logo_url: "https://via.placeholder.com/150?text=Analyst",
    bonus: "Expert analysis, withdrawal guides, promo code database",
    license: "N/A",
    description: "Professional casino analysis site offering expert reviews, detailed pros and cons, withdrawal assistance guides, comprehensive promo code database, and alternative recommendations.",
    country: undefined,
    payment_methods: undefined,
    rating_avg: 4.5,
    rating_count: 124,
    entry_type: "review-site",
    external_url: "https://example.com/analyst-pro",
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "demo-6c",
    name: "Casino Guide Hub",
    slug: "casino-guide-hub",
    logo_url: "https://via.placeholder.com/150?text=Guide",
    bonus: "Registration help, withdrawal support, detailed reviews",
    license: "N/A",
    description: "Your complete guide to online casinos. Provides step-by-step registration help, withdrawal assistance, detailed reviews with pros and cons, and exclusive promo codes.",
    country: undefined,
    payment_methods: undefined,
    rating_avg: 4.3,
    rating_count: 98,
    entry_type: "review-site",
    external_url: "https://example.com/guide-hub",
    verified: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
